### ISSUE TITLE
A question for GWB in ASPECT

### ISSUE THREAD

**Issue by sungho91** [GeodynamicWorldBuilder/WorldBuilder#145]
Hi 

This is Sungho Lee. 

I have temperature field data which is driven by tomography and I have implemented it into ASPECT using the Initial temperature model (ASCII data).

Then, I've performed instantaneous modeling for studying the effect of temperature anomaly on stress field.  

However, my problem is the data has no coverage to near subduction slab (pacific). 

I want to consider the slab using GWB. 

It is possible to use both the initial temperature model from GWB and the initial temperature model (ASCII) together in ASPECT?

**Comment by MFraters** [comment]
Hey Sungho Lee,
I see no reason why you could not write a plugin which uses both the world builder and ASCII data together in ASPECT as long as you have a good idea what you want to use where. If you are interested in doing this, it might be a good idea to open an issue in the aspect repository so that other aspect developers and comment as well. 

One thing you might want to think about is what slab temperature structure you want to prescribe. Currently the McKenzie 1970 temperature is implemented for slabs, but depending on you application you might want something different.
