### ISSUE TITLE
Variable top subducting plate temperature 

### ISSUE THREAD

**Issue by Pedrogea08** [GeodynamicWorldBuilder/WorldBuilder#234]
Hello everyone!
I want to use the linear temperature model in a subducting plate. In doing so, I have to write a top temperature which will be constant along the top layer of the subducting plate. However, I want it to change with the depth of the top layer of the subducting plate. Is there any possibilitie to do that?
Thanks !!

**Comment by MFraters** [comment]
Hey,

Thanks for you question! It is currently not implemented to parse functions as inputs, but it should be really easy to add the depth dependency to your own temperature plugin if you know some basic c++. 

If you don't want to write your own plugin, I would need to add a function parser to the world builder so that you can add your equation of how the temperature should depend on depth. This will take a bit of research and work and I don't know when I would get around to adding it, but I think it would be a useful new feature to add to the world builder.

I hope this helps, let me know if you have any further questions!

**Comment by MFraters** [comment]
I have looked a little bit into math parsers and I think the way to go with with the muparser (https://beltoforion.de/en/muparser/). This is the same parser Deal.ii and ASPECT use and it looks like it would be easy to add to the world builder.

**Comment by MFraters** [comment]
Feel free to reopen if this is still an issue.
