### ISSUE TITLE
Spatially Dependent Spreading Rates

### ISSUE THREAD

**Issue by danieldouglas92** [GeodynamicWorldBuilder/WorldBuilder#533]
When defining a ridge, the spreading rate is assumed to be constant along the length of the entire feature. For some spreading centers, this is unrealistic (like the Lau spreading center), where there is a substantial decrease in spreading rate south along the ridge. To avoid having to manually break up a single ridge into multiple smaller ridges, each with it's own manually defined constant spreading rate, it would be smoother to implement a way to linearly change the spreading rate from v1 at ridge coordinate (x1, y1), to v2 at ridge coordinate (x2, y2).

The input for this in the temperature features could just expand the "spreading velocity" parameter into an array. This array would be of length N, where N is the number of user defined "ridge coordinates". 

`"ridge coordinates":[[[x1, y1], [x2, y2], ..., [xn, yn]]]`
`"spreading velocity":[v1, v2, ..., vn]`

And the spreading velocity would be linearly interpolated from `v1` to `v2` from `[x1, y1], [x2, y2]`, and then `v2` to `v3` from `[x2, y2], [x3, y3]` etc. If the user inputs a single value for `"spreading velocity"`, a constant value is used for the entire ridge feature.

**Comment by MFraters** [comment]
Thanks for making the issue! I have been separately thinking about temporary varying spreading velocities. What you could do for now is just add an extra [[]] around the spreading velocities, so that in the future we could implement something like `"spreading velocity":[[0,[v1, v2, ..., vn]],[50e3,[v1, v2, ..., vn]]]`

This would then give us the following variants: 
1. no variation: `"spreading velocity":1e-2` or `"spreading velocity":[[[1e-2]]]`
2. temporal variation: `"spreading velocity":[[0,[1e-2]],[50e3,[5e-2]]]`
3. spatial variation:  `"spreading velocity":[[[1e-2,5e-2, 2.5e-2]]]`
4. temporal and spatial variation:  `"spreading velocity":[[0,[1e-2,5e-2, 2.5e-2]],[50e3,[2e-2,6e-2, 7.5e-2]]]`

What do you think? Will this become too complicated? Just to reterate, you would not have to implement case 2 and 4, but just design it in a way it would become possible to add it on later without breaking input files.

**Comment by danieldouglas92** [comment]
I think that that sounds good! Also nice that it has a similar syntax as the variable overriding plate thickness
