### ISSUE TITLE
check if `choco install swig` is not a virus

### ISSUE THREAD

**Issue by gogo2464** [GeodynamicWorldBuilder/WorldBuilder#760]
In the official doc I read the command `choco install swig` marked as safe there:
https://gwb.readthedocs.io/en/v1.0.0/user_manual/installation/installing_prerequisites.html . Could we just link the doc of swig to ensure it is not a malware and they really want to put this in devops please?

Best regards.

**Comment by gogo2464** [comment]
I want to ensure it is not a virus!

**Comment by MFraters** [comment]
Hey @gogo2464,

Thanks for your question. SWIG is an open source program to automatically make python binding from C or C++. You can find the website here: https://swig.org/ and the github here: https://github.com/swig/swig. SWIG is distributed in in most, if not all, linux package managers, in brew for OSX and choco for windows. So I would say that means SWIG is generally well trusted. Furthermore, given it's open source nature it is generally trusted, because if you want to check the code yourself you can. Note that if do not need the python bindings, you do not need to install swig.

If you need python bindings do not trust SWIG and you do need to use python binding, you would need to write them yourself. If you do not trust the choco package manager on windows, you can install swig directly from the source code, as explained on their github: https://github.com/swig/swig.

I hope this answers your question and let me know if anything is still unclear. Also feel free to make a pull request to update the documentation so that it would be more clear to you!

**Comment by gogo2464** [comment]
Hello :)

Thank you very much for the answer and the attention. SWIG is very serious yes! But is the swig chocolatey package made by swig people? I do not find any mention of choco in the swig doc. There may be a third party person that could package swig instead of swig people in  order to inject a malware in the swig code.

It is a very common way to spread malware. I even got one like this on my computer.

I just would like to know if there could be a link to the swig doc that mention the usage of choco for swig please? I will be really happier and less stressed.

**Comment by MFraters** [comment]
According to the swig page on chocolatery (https://community.chocolatey.org/packages/swig) the package is maintained by kylewm, xoviat and chrisdembia, where the package source is hosted by xoviat: https://bitbucket.org/xoviat/chocolatey-packages/src/master/, which I do not see see as names of contributors in the github repository. Looking at the installer in the package source for the latest swig (https://bitbucket.org/xoviat/chocolatey-packages/src/master/swig/4.1.1/tools/chocolateyinstall.ps1) it just downloads the latest swigwin zip from the official sourceforge: https://sourceforge.net/projects/swig/files/swigwin/swigwin-4.2.1/, which the official swig.org website also redirects you to: https://www.swig.org/download.html. 

So in short, it doesn't appear that the package maintainers are the same people that develop and maintain swig. I have to say that this is actually quite common in the open source world. Looking at the package itself, I don't see anything strange, and it looks like chocolatery is actually scanning the packages for malware, but these things can always change without warning and in the end you will have to decide yourself if this is oke for you or not. 

It actually looks quite easy to install swig without chocolatery with the swigwin zip, which is provided by the swig maintainers, so I guess that would be the most "secure" way to install swig if you don't trust the chocolatery and their virus scan and do not want to compile swig from source.

**Comment by MFraters** [comment]
I am assuring this is resolved. Feel free to reopen if you have any further questions or concerns.

**Comment by gogo2464** [comment]
It could be still great to build chocolatey from cicd and document it existence on the repo.
